from tkinter import *
from tkinter import Radiobutton,Spinbox,messagebox
from tkinter.ttk import *
window = Tk()
window.title("Register")
window.geometry("800x600")
head = Label(window,text="Register")
head.grid(column=4,row=0)
lbl = Label(window,text="Name")
lbl.grid(column=0,row=100)
txt = Entry(window,width=20)
txt.grid(column=1,row=100)
names = txt.get()
lbl1 = Label(window,text="Gender")
lbl1.grid(column=0,row=200)
selected =StringVar()
radio = Radiobutton(window,text="male",value="male",variable=selected)
radio.grid(column=1,row=200)
radio = Radiobutton(window,text="female",value="female",variable=selected)
radio.grid(column=2,row=200)
lbl2 = Label(window,text="Age")
lbl2.grid(column=0,row=300)
box = Spinbox(window,from_=1,to=100,width=20)
box.grid(column=1,row=300)
lbl3 = Label(window,text="Country")
lbl3.grid(column=0,row=400)
combo = Combobox(window)
combo['value'] = ("select","India","China","Japan","UAE")
combo.current(0)
combo.grid(column=1,row=400)
lbl4 = Label(window,text="Hobby")
lbl4.grid(column=0,row=500)
chk = BooleanVar()
chk.set(0)
check = Checkbutton(window,text="Football",va=chk,onvalue=1,offvalue=0)
check.grid(column=1,row=500)
chk1 = BooleanVar()
chk1.set(0)
check1 = Checkbutton(window,text="Cricket",va=chk1,onvalue=1,offvalue=0)
check1.grid(column=2,row=500)
chk2 = BooleanVar()
chk2.set(0)
check2 = Checkbutton(window,text="Movies",va=chk2,onvalue=1,offvalue=0)
check2.grid(column=3,row=500)
def register(txt):
    msg = messagebox.showinfo('success','Registration succesfull..')
    window = Tk()
    window.title("Registration done")
    window.geometry("500x400")
    name = Label(window,text="name")
    name.grid(row=0,column=0)
    res = "Name:   "+txt.get()
    names = name.configure(text=res)
    gender  = Label(window,text="gender")
    gender.grid(row=1,column=0)
    gen = "Gender:   "+selected.get()
    genders = gender.configure(text=gen)
    Age = Label(window,text="Age")
    Age.grid(row=2,column=0)
    age = "Age:   "+box.get()
    ages = Age.configure(text=age)
    country = Label(window,text="country")
    country.grid(row=3,column=0)
    co = "Country:   "+combo.get()
    lbl = Label(window,text="Hobbies:   ")
    lbl.grid(row=4,column=0)
    coun = country.configure(text=co)
    foot = chk.get()
    cri = chk1.get()
    mov = chk2.get()
    if foot == 1:
        value = "football,"
        football = Label(window,text="Football")
        football.grid(row=4,column=1)
        foots = football.configure(text=value)
    if cri == 1:
        value1 = "cricket,"
        cricket = Label(window,text="Cricket")
        cricket.grid(row=4,column=2)
        cric = cricket.configure(text=value1)
    if mov == 1:
        value2 = "movies,"
        movies = Label(window,text="Movies")
        movies.grid(row=4,column=3)
        movie = movies.configure(text=value2)
   
btn = Button(window,text="register",command=lambda:register(txt))
btn.grid(column=2,row=600)
